name: CD Auth microservice

on:
  push:
    branches:
      - cicd

jobs:
  docker-image-build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: ./dist

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: shashwotbhattarai/auth_microservice

      - name: Verify Pushed Image
        run: docker pull shashwotbhattarai/auth_microservice
