name: Node.js Unit Tests

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd
  workflow_run:
    workflows: ["Node.js Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Download build results
        uses: actions/download-artifact@v2
        with:
          name: build-results
          path: ./build-results

      - name: Run unit tests
        run: npm test
